/**
 * @fileoverview 留言板模板
 * @author geekzl<1103307205@qq.com>
 * @date 2017/07/03
 */
define('template/article', function(require, exports, module) {

    /* beautify ignore:start */
    /* eslint-disable */
    var tpl = [
        '<div class="container">',
            '<div class="row">',
                '<div class="col-md-12">',
                    '<div class="article post-article clearfix">',
                        '<div class="post-head clearfix">',
                            '<div class="post-title">',
                                '<h4>{{title}}</h4>',
                            '</div>',
                            '<div class="post-return">',
                            '<a href="#/article" class="post-return-a"><<返回文章列表</a>',
                            '</div>',
                            '<div class="post-meta">',
                                '<p class="subhead"><span>作者：{{username}}</span>&nbsp<span>最后编辑于 {{time}}</span></p>',
                            '</div>',
                        '</div>',
                        '<div class="post-abs" v-html="intro"></div>',
                        '<div class="post-cont" v-html="cont"></div>',
                        '<div class="post-footer clearfix">',
                            '<p>版权所有，转载注明出处</p>',
                        '</div>',
                        '<div class="comment">',
                            '<div class="head">',
                                '<h3>留言（30条）</h3>',
                            '</div>',
                            '<div class="wrap">',
                                '<ul>',
                                    '<li>',
                                        '<div class="cont clearfix">',
                                            '<div class="title">',
                                                '<span>张三 说</span>',
                                            '</div>',
                                            '<div class="content">',
                                                '<p>内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容</p>',
                                            '</div>',
                                            '<div class="foot">',
                                                '<p><span>2017年8月29日 17:36</span> | <span>引用</span></p>',
                                            '</div>',
                                        '</div>',
                                    '</li>',
                                '</ul>',
                            '</div>',
                            '<div class="comments-reply">',
                                '<h3 class="comments-title">我要发表看法</h3>',
                                '<div class="comments-content">',
                                    '<form method="post" action="http://blog.feroad.com/article/addMark" name="comments_form" id="comments-form" onsubmit="updateComents();">',
                                        '<input type="hidden" v-model="comment.id">',
                                        '<div id="comments-open-data">',
                                            '<div class="comments-open-text">',
                                                '<p><label for="comment-text">您的留言</label></p>',
                                                '<p><textarea id="comment-text" name="text" rows="10" cols="50" v-html="comment.content"></textarea></p>',
                                            '</div>',
                                            '<div id="comment-form-name">',
                                                '<p><label for="comment-author">您的大名：</label></p>',
                                                '<p><input id="comment-author" name="author" size="30" v-model="comment.nickname">',
                                                    '<span class="hint"> «-必填</span></p>',
                                            '</div>',
                                            '<div id="comment-form-email">',
                                                '<p><label for="comment-email">电子邮件：</label></p>',
                                                '<p><input id="comment-email" name="email" size="30" v-model="comment.email">',
                                                    '<span class="hint"> «-必填，不公开</span></p>',
                                            '</div>',
                                            '<div id="comment-form-url">',
                                                '<p><label for="comment-url">个人网址：</label></p>',
                                                '<p><input id="comment-url" name="url" size="30" v-model="comment.website">',
                                                    '<span class="hint"> «-你的个人网址</span></p>',
                                            '</div>',
                                            '<div id="comment-form-remember-me">',
                                                '<p>',
                                                    '<label for="comment-bake-cookie">记住个人信息？</label>',
                                                    '<input type="checkbox" id="comment-bake-cookie" name="bakecookie" onclick="saveCookie(this.checked)">',
                                                '</p>',
                                            '</div>',
                                        '</div>',
                                        '<div id="comments-open-footer">',
                                            '<p>',
                                                '<input type="submit" name="post" class="submit btn btn-primary" value="发表">',
                                                '<span class="hint"> «- 点击按钮</span>',
                                            '</p>',
                                        '</div>',
                                    '</form>',
                                '</div>',
                            '</div>',
                        '</div>',
                    '</div>',
                '</div>',
            '</div>',
        '</div>',
    ].join('');
    /* beautify ignore:end */
    /* eslint-disable */

    module.exports = tpl;

});
