/**
 * @fileoverview 留言板模板
 * @author geekzl<1103307205@qq.com>
 * @date 2017/07/03
 */
define('template/article', function(require, exports, module) {

    /* beautify ignore:start */
    /* eslint-disable */
    var tpl = [
        '<div class="container">',
            '<div class="row">',
                '<div class="col-md-12">',
                    '<div class="article post-article clearfix">',
                        '<div class="post-head clearfix">',
                            '<div class="post-title">',
                                '<h4>{{title}}</h4>',
                            '</div>',
                            '<div class="post-return">',
                            '<a href="#/article" class="post-return-a"><<返回文章列表</a>',
                            '</div>',
                            '<div class="post-meta">',
                                '<p class="subhead"><span>作者：{{username}}</span>&nbsp<span>最后编辑于 {{time}}</span></p>',
                            '</div>',
                        '</div>',
                        '<div class="post-abs" v-html="intro"></div>',
                        '<div class="post-cont" v-html="cont"></div>',
                        '<div class="post-footer clearfix">',
                            '<p>版权所有，转载注明出处</p>',
                        '</div>',
                        '<div class="comment">',
                            '<div v-if="comments.length">',
                                '<div class="head">',
                                    '<h3>评论（{{comments.length}}条）</h3>',
                                '</div>',
                                '<div class="wrap">',
                                    '<ul>',
                                        '<li v-for="item in comments">',
                                            '<div class="cont clearfix">',
                                                '<div class="title">',
                                                    '<span v-if="item.website"><a :href="item.website" target="_blank">{{item.nickname}}</a> 说</span>',
                                                    '<span v-else>{{item.nickname}} 说</span>',
                                                '</div>',
                                                '<div class="content">',
                                                    '<div v-html="item.content"></div>',
                                                '</div>',
                                                '<div class="foot">',
                                                    '<p>',
                                                        '<span class="expression">',
                                                            '<i class="glyphicon glyphicon-thumbs-up" :class="{visited:item.isVisted}" @click.stop="support(item)"></i>',
                                                            '<i>{{item.supNum}}</i>',
                                                        '</span>',
                                                        '<span>{{transferTime(item.create_time)}}</span>',
                                                    '</p>',
                                                '</div>',
                                            '</div>',
                                        '</li>',
                                    '</ul>',
                                '</div>',
                            '</div>',
                            '<div class="comments-reply">',
                                '<h3 class="comments-title">我要发表看法</h3>',
                                '<div class="comments-content">',
                                    '<form>',
                                        '<div id="comments-open-data">',
                                            '<div class="comments-open-text">',
                                            '<p><label for="comment-text">您的评论</label></p>',
                                            '<p>',
                                                '<textarea rows="10" cols="50" v-model="comment.content"></textarea>',
                                            '</p>',
                                            '<p v-if="comment.errTip" class="errorCls"><span>{{comment.errTip}}</span></p>',
                                            '</div>',
                                            '<div id="comment-form-name">',
                                                '<p><label for="comment-author">您的大名：</label></p>',
                                                '<p>',
                                                    '<input size="30" v-model="comment.nickname">',
                                                    '<span class="hint"> «-必填</span>',
                                                '</p>',
                                            '</div>',
                                            '<div id="comment-form-email">',
                                                '<p><label for="comment-email">电子邮件：</label></p>',
                                                '<p>',
                                                    '<input size="30" v-model="comment.email">',
                                                    '<span class="hint"> «-必填，不公开</span>',
                                                '</p>',
                                            '</div>',
                                            '<div id="comment-form-url">',
                                                '<p><label for="comment-url">个人网址：</label></p>',
                                                '<p>',
                                                    '<input size="30" placeholder="如：www.baidu.com" v-model="comment.website">',
                                                    '<span class="hint"> «-你的个人网址</span>',
                                                '</p>',
                                            '</div>',
                                            '<div id="comment-form-remember-me">',
                                                '<p>',
                                                    '<label for="comment-bake-cookie">记住个人信息？</label>',
                                                    '<input type="checkbox" :data-state="comment.state" @click="saveCookie()">',
                                                '</p>',
                                            '</div>',
                                        '</div>',
                                        '<div id="comments-open-footer">',
                                            '<p>',
                                                '<button class="submit btn btn-primary" @click="updateComments">发表</button>',
                                                '<span class="hint"> «- 点击按钮</span>',
                                            '</p>',
                                        '</div>',
                                    '</form>',
                                '</div>',
                            '</div>',
                        '</div>',
                    '</div>',
                '</div>',
            '</div>',
        '</div>',
    ].join('');
    /* beautify ignore:end */
    /* eslint-disable */

    module.exports = tpl;

});
